{
    'name': 'Aset Bangunan',
    'version': '12.0.1.0.0',
    'description': 'Master Data Bangunan',
    'summary': 'Master Data Bangunan',
    'author': 'Gosantha',
    'website': 'http://www.gosantha.com',
    'license': 'LGPL-3',
    'category': 'Extra Tools',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'data/seq.xml',
        'views/area.xml',
        'views/zona.xml',
        'views/bangunan.xml',
        'views/lantai.xml',
        'views/ruang.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'auto_install': False,
    'application': True,
    'installable': True,
}